### ISSUE TITLE
two issues against android Chrome 51.0.2704.81

### ISSUE THREAD

**Issue by siruzhou** [popfeng/zao#1]
升级了一下android手机的chrome浏览器，没注意升级前的版本是多少，升级后版本 51.0.2704.81，
然后出现了两个问题：
1.) 音频无法后台播放，貌似是chrome半年前引入的一个新功能。没找到开关选项，目前只能开着屏幕，放在前台。
     https://codereview.chromium.org/1292433002/
2.) 音乐播放器进度条拖动无效。

解决办法：
试了一款国产浏览器，没有上面的问题。

**Comment by popfeng** [comment]
Get, tks

**Comment by siruzhou** [comment]
小众浏览器的问题，低优先级 ：）
